#!/bin/bash

#The aim for this script is to create text file with list of files from data dir
# it writes the list to a file denoted by supplied cmd argument
rm -f $1
touch $1
for x in `find ./data/* -type f`
do
echo "$x" >> $1
done
